# Generated by Django 5.1.4 on 2025-01-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualification_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
