# Generated by Django 5.1.4 on 2025-01-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_site', '0003_alter_doctor_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='dosage_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='prescriptions',
            name='dosage_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
