# Generated by Django 5.1.4 on 2025-01-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_site', '0004_prescriptions_dosage_en_prescriptions_dosage_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='doctor_en',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='doctor_ru',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='patient_en',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='patient_ru',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='shift_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='shift_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='dosage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='dosage_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='dosage_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
